window.BOOKS_MANIFEST = [
  {
    slug: "a-arte-de-fazer-acontecer",
    file: "a-arte-de-fazer-acontecer.md",
    title: "A Arte de Fazer Acontecer",
    author: "David Allen",
    year: 2001,
    category: "Produtividade",
    minutes: 15,
    hook: "Sua mente serve para ter ideias, não para guardá-las.",
    summary: "David Allen oferece um sistema prático para reduzir sobrecarga mental e aumentar clareza sobre o que fazer.",
    tags: ["gtd", "organização", "produtividade"],
    file_en: "a-arte-de-fazer-acontecer-en.md",
    title_en: "Getting Things Done",
    category_en: "Productivity",
    hook_en: "Your brain is for having ideas, not holding them.",
    summary_en: "David Allen offers a practical system for reducing mental overload and increasing clarity about what to do.",
    tags_en: ["gtd", "organization", "productivity"]
  },
  {
    slug: "as-armas-da-persuasao",
    file: "as-armas-da-persuasao.md",
    title: "As Armas da Persuasão",
    author: "Robert B. Cialdini",
    year: 1984,
    category: "Psicologia",
    minutes: 15,
    hook: "Sete gatilhos automáticos guiam boa parte das nossas decisões de “sim”.",
    summary: "Cialdini identifica princípios universais de influência que funcionam de forma inconsciente.",
    tags: ["persuasão", "influência", "psicologia"],
    file_en: "as-armas-da-persuasao-en.md",
    title_en: "Influence",
    category_en: "Psychology",
    hook_en: "Seven automatic triggers guide most of our “yes” decisions.",
    summary_en: "Cialdini identifies universal principles of influence that work unconsciously.",
    tags_en: ["persuasion", "influence", "psychology"]
  },
  {
    slug: "os-7-habitos",
    file: "os-7-habitos.md",
    title: "Os 7 Hábitos das Pessoas Altamente Eficazes",
    author: "Stephen R. Covey",
    year: 1989,
    category: "Negócios",
    minutes: 15,
    hook: "Eficácia real vem de dentro para fora.",
    summary: "Covey organiza sete hábitos que levam de dependência a interdependência sustentável.",
    tags: ["eficácia", "desenvolvimento", "liderança"],
    file_en: "os-7-habitos-en.md",
    title_en: "The 7 Habits of Highly Effective People",
    category_en: "Business",
    hook_en: "Real effectiveness comes from the inside out.",
    summary_en: "Covey organizes seven habits that move from dependence to sustainable interdependence.",
    tags_en: ["effectiveness", "development", "leadership"]
  },
  {
    slug: "rapido-e-devagar",
    file: "rapido-e-devagar.md",
    title: "Rápido e Devagar",
    author: "Daniel Kahneman",
    year: 2011,
    category: "Psicologia",
    minutes: 15,
    hook: "Sua mente tem dois sistemas: um rápido e intuitivo, outro lento e deliberativo.",
    summary: "Kahneman descreve como vieses cognitivos sistemáticos afetam nossas decisões.",
    tags: ["vieses", "decisão", "psicologia"],
    file_en: "rapido-e-devagar-en.md",
    title_en: "Thinking, Fast and Slow",
    category_en: "Psychology",
    hook_en: "Your mind has two systems: one fast and intuitive, one slow and deliberate.",
    summary_en: "Kahneman describes how systematic cognitive biases affect our decisions.",
    tags_en: ["biases", "decision", "psychology"]
  },
  {
    slug: "habitos-atomicos",
    file: "habitos-atomicos.md",
    title: "Hábitos Atômicos",
    author: "James Clear",
    year: 2018,
    category: "Produtividade",
    minutes: 15,
    hook: "Você não sobe ao nível das suas metas — você cai ao nível dos seus sistemas.",
    summary: "James Clear mostra que mudanças reais acontecem menos por força de vontade e mais por estruturas simples que reduzem a fricção do hábito desejado.",
    tags: ["hábitos", "sistemas", "mudança"],
    file_en: "habitos-atomicos-en.md",
    title_en: "Atomic Habits",
    category_en: "Productivity",
    hook_en: "You do not rise to the level of your goals — you fall to the level of your systems.",
    summary_en: "James Clear shows that real change happens less through willpower and more through simple structures that reduce friction for the desired habit.",
    tags_en: ["habits", "systems", "change"]
  },
  {
    slug: "deep-work",
    file: "deep-work.md",
    title: "Deep Work",
    author: "Cal Newport",
    year: 2016,
    category: "Produtividade",
    minutes: 15,
    hook: "Atenção sem distração é a superhabilidade do século XXI.",
    summary: "Cal Newport argumenta que o trabalho profundo se tornou raro e extremamente valioso.",
    tags: ["foco", "atenção", "carreira"],
    file_en: "deep-work-en.md",
    title_en: "Deep Work",
    category_en: "Productivity",
    hook_en: "Attention without distraction is the superpower of the 21st century.",
    summary_en: "Cal Newport argues that deep work has become rare and extremely valuable.",
    tags_en: ["focus", "attention", "career"]
  },
  {
    slug: "essencialismo",
    file: "essencialismo.md",
    title: "Essencialismo",
    author: "Greg McKeown",
    year: 2014,
    category: "Produtividade",
    minutes: 15,
    hook: "Se não é um “hell yes”, é um não.",
    summary: "Greg McKeown defende que a produtividade real vem da disciplina de dizer não.",
    tags: ["prioridade", "disciplina", "foco"],
    file_en: "essencialismo-en.md",
    title_en: "Essentialism",
    category_en: "Productivity",
    hook_en: "If it is not a “hell yes”, it is a no.",
    summary_en: "Greg McKeown argues that real productivity comes from the discipline of saying no.",
    tags_en: ["priority", "discipline", "focus"]
  },
  {
    slug: "o-poder-do-habito",
    file: "o-poder-do-habito.md",
    title: "O Poder do Hábito",
    author: "Charles Duhigg",
    year: 2012,
    category: "Produtividade",
    minutes: 15,
    hook: "Gatilho, rotina, recompensa — o loop que governa metade da sua vida.",
    summary: "Duhigg mostra como hábitos se formam e se mantêm por meio de um loop simples.",
    tags: ["hábito", "loop", "mudança"],
    file_en: "o-poder-do-habito-en.md",
    title_en: "The Power of Habit",
    category_en: "Productivity",
    hook_en: "Cue, routine, reward — the loop that governs half of your life.",
    summary_en: "Duhigg shows how habits form and persist through a simple loop.",
    tags_en: ["habit", "loop", "change"]
  },
  {
    slug: "mindset",
    file: "mindset.md",
    title: "Mindset",
    author: "Carol Dweck",
    year: 2006,
    category: "Psicologia",
    minutes: 15,
    hook: "Ainda não é um veredicto — é o próximo passo.",
    summary: "Carol Dweck conecta a forma como pensamos sobre talento e esforço com o desenvolvimento humano.",
    tags: ["crescimento", "aprendizagem", "resiliência"],
    file_en: "mindset-en.md",
    title_en: "Mindset",
    category_en: "Psychology",
    hook_en: "It is not a verdict yet — it is the next step.",
    summary_en: "Carol Dweck connects how we think about talent and effort with human development.",
    tags_en: ["growth", "learning", "resilience"]
  },
  {
    slug: "inteligencia-emocional",
    file: "inteligencia-emocional.md",
    title: "Inteligência Emocional",
    author: "Daniel Goleman",
    year: 1995,
    category: "Psicologia",
    minutes: 15,
    hook: "QI te leva à entrevista; QE te faz ficar.",
    summary: "Goleman destaca que as habilidades emocionais são tão importantes quanto a inteligência técnica.",
    tags: ["emoções", "empatia", "liderança"],
    file_en: "inteligencia-emocional-en.md",
    title_en: "Emotional Intelligence",
    category_en: "Psychology",
    hook_en: "IQ gets you the interview; EQ keeps you there.",
    summary_en: "Goleman highlights that emotional skills are as important as technical intelligence.",
    tags_en: ["emotions", "empathy", "leadership"]
  },
  {
    slug: "flow",
    file: "flow.md",
    title: "Flow",
    author: "Mihaly Csikszentmihalyi",
    year: 1990,
    category: "Psicologia",
    minutes: 15,
    hook: "Felicidade não é encontrada — é construída na atenção.",
    summary: "Csikszentmihalyi investiga o estado de absorção plena em que a pessoa se sente inteiramente engajada.",
    tags: ["fluxo", "atenção", "sentido"],
    file_en: "flow-en.md",
    title_en: "Flow",
    category_en: "Psychology",
    hook_en: "Happiness is not found — it is built in attention.",
    summary_en: "Csikszentmihalyi studies the deeply absorbing state in which a person feels fully engaged.",
    tags_en: ["flow", "attention", "meaning"]
  },
  {
    slug: "grit",
    file: "grit.md",
    title: "Grit",
    author: "Angela Duckworth",
    year: 2016,
    category: "Psicologia",
    minutes: 15,
    hook: "Talento × esforço = habilidade. Habilidade × esforço = conquista.",
    summary: "Angela Duckworth mostra que perseverança e paixão podem explicar muito do sucesso.",
    tags: ["perseverança", "esforço", "paixão"],
    file_en: "grit-en.md",
    title_en: "Grit",
    category_en: "Psychology",
    hook_en: "Talent × effort = skill. Skill × effort = achievement.",
    summary_en: "Angela Duckworth shows that perseverance and passion can explain much of success.",
    tags_en: ["perseverance", "effort", "passion"]
  },
  {
    slug: "em-busca-de-sentido",
    file: "em-busca-de-sentido.md",
    title: "Em Busca de Sentido",
    author: "Viktor Frankl",
    year: 1946,
    category: "Psicologia",
    minutes: 15,
    hook: "Mesmo no extremo da dor, o sentido interior pode ser conservado.",
    summary: "Frankl mostra como a busca de sentido sustenta a liberdade interior mesmo nas piores circunstâncias.",
    tags: ["sentido", "sofrimento", "psicologia"],
    file_en: "em-busca-de-sentido-en.md",
    title_en: "Man's Search for Meaning",
    category_en: "Psychology",
    hook_en: "Even at the extreme edge of pain, inner meaning can be preserved.",
    summary_en: "Frankl explains how the search for meaning sustains inner freedom even in extreme suffering.",
    tags_en: ["meaning", "suffering", "psychology"]
  },
  {
    slug: "comece-pelo-porque",
    file: "comece-pelo-porque.md",
    title: "Comece Pelo Porquê",
    author: "Simon Sinek",
    year: 2009,
    category: "Negócios",
    minutes: 15,
    hook: "Pessoas não compram o que você faz — compram por que você faz.",
    summary: "Sinek mostra como líderes e marcas ganham força quando partem de uma ideia central clara.",
    tags: ["propósito", "liderança", "marca"],
    file_en: "comece-pelo-porque-en.md",
    title_en: "Start with Why",
    category_en: "Business",
    hook_en: "People do not buy what you do — they buy why you do it.",
    summary_en: "Sinek shows how leaders and brands gain power when they start from a clear why.",
    tags_en: ["purpose", "leadership", "brand"]
  },
  {
    slug: "codigo-limpo",
    file: "codigo-limpo.md",
    title: "Código Limpo",
    author: "Robert C. Martin",
    year: 2008,
    category: "Tecnologia",
    minutes: 15,
    hook: "Código é lido dez vezes mais do que é escrito. Escreva para o leitor.",
    summary: "Martin reúne princípios práticos para escrever software mais legível, sustentável e fácil de manter.",
    tags: ["engenharia", "manutenção", "craft"],
    file_en: "codigo-limpo-en.md",
    title_en: "Clean Code",
    category_en: "Technology",
    hook_en: "Code is read ten times more than it is written. Write for the reader.",
    summary_en: "Martin gathers practical principles for writing software that is readable, sustainable and easy to maintain.",
    tags_en: ["engineering", "maintenance", "craft"]
  },
  {
    slug: "etica-a-nicomaco",
    file: "etica-a-nicomaco.md",
    title: "Ética a Nicômaco",
    author: "Aristóteles",
    year: -340,
    category: "Filosofia",
    minutes: 15,
    hook: "A vida boa é construída pela prática constante das virtudes.",
    summary: "Aristóteles descreve a vida ética como o equilíbrio virtuoso entre excesso e falta e como o caráter se forma pela prática.",
    tags: ["ética", "virtude", "filosofia"],
    file_en: "etica-a-nicomaco-en.md",
    title_en: "Nicomachean Ethics",
    category_en: "Philosophy",
    hook_en: "The good life is built by the constant practice of virtues.",
    summary_en: "Aristotle describes ethical life as the virtuous balance between excess and deficiency and how character is formed through practice.",
    tags_en: ["ethics", "virtue", "philosophy"]
  },
  {
    slug: "agile-testing",
    file: "agile-testing.md",
    title: "Agile Testing",
    author: "Lisa Crispin & Janet Gregory",
    year: 2008,
    category: "Tecnologia",
    minutes: 15,
    hook: "Qualidade é construída em cada sprint, não só no fim do projeto.",
    summary: "A abordagem mostra que QA e desenvolvimento trabalham juntos desde o começo.",
    tags: ["agile", "qualidade", "teste"],
    file_en: "agile-testing-en.md",
    title_en: "Agile Testing",
    category_en: "Technology",
    hook_en: "Quality is built in every sprint, not only at the end of the project.",
    summary_en: "The approach shows QA and development working together from the start.",
    tags_en: ["agile", "quality", "testing"]
  },
  {
    slug: "continuous-delivery",
    file: "continuous-delivery.md",
    title: "Continuous Delivery",
    author: "Jez Humble & David Farley",
    year: 2010,
    category: "Tecnologia",
    minutes: 15,
    hook: "Entrega frequente exige automação, confiança e fluxo contínuo.",
    summary: "O livro mostra como reduzir risco de release com automação e feedback contínuo.",
    tags: ["devops", "entrega", "automação"],
    file_en: "continuous-delivery-en.md",
    title_en: "Continuous Delivery",
    category_en: "Technology",
    hook_en: "Frequent delivery requires automation, trust and continuous flow.",
    summary_en: "The book shows how to reduce release risk with automation and continuous feedback.",
    tags_en: ["devops", "delivery", "automation"]
  },
  {
    slug: "perfect-software",
    file: "perfect-software.md",
    title: "Perfect Software",
    author: "Roger S. Pressman",
    year: 2005,
    category: "Tecnologia",
    minutes: 15,
    hook: "Software perfeito não é ausência de defeitos, mas uma estratégia de excelência.",
    summary: "O texto reforça que qualidade depende de processos, disciplina e visão sistêmica.",
    tags: ["qualidade", "processo", "software"],
    file_en: "perfect-software-en.md",
    title_en: "Perfect Software",
    category_en: "Technology",
    hook_en: "Perfect software is not the absence of defects, but a strategy of excellence.",
    summary_en: "Perfect software depends on processes, discipline and systems thinking.",
    tags_en: ["quality", "process", "software"]
  },
  {
    slug: "a-coragem-de-ser-imperfeito",
    file: "a-coragem-de-ser-imperfeito.md",
    title: "A Coragem de Ser Imperfeito",
    author: "Brené Brown",
    year: 2012,
    category: "Psicologia",
    minutes: 13,
    hook: "Vulnerabilidade não é fraqueza — é a medida mais precisa da coragem.",
    summary: "Brené Brown desmistifica a vulnerabilidade como fonte de criatividade, conexão e liderança autêntica.",
    tags: ["vulnerabilidade", "coragem", "desenvolvimento"],
    file_en: "a-coragem-de-ser-imperfeito-en.md",
    title_en: "Daring Greatly",
    category_en: "Psychology",
    hook_en: "Vulnerability is not weakness—it's the most accurate measure of courage.",
    summary_en: "Brené Brown demystifies vulnerability as a source of creativity, connection, and authentic leadership.",
    tags_en: ["vulnerability", "courage", "development"]
  },
  {
    slug: "agilidade-emocional",
    file: "agilidade-emocional.md",
    title: "Agilidade Emocional",
    author: "Susan David",
    year: 2016,
    category: "Psicologia",
    minutes: 12,
    hook: "Suas emoções são dados, não diretrizes.",
    summary: "Susan David ensina a conviver com sentimentos difíceis sem ser governado por eles.",
    tags: ["emoções", "resiliência", "valores"],
    file_en: "agilidade-emocional-en.md",
    title_en: "Emotional Agility",
    category_en: "Psychology",
    hook_en: "Your emotions are data, not directives.",
    summary_en: "Susan David teaches how to live with difficult feelings without being governed by them.",
    tags_en: ["emotions", "resilience", "values"]
  },
  {
    slug: "comunicacao-nao-violenta",
    file: "comunicacao-nao-violenta.md",
    title: "Comunicação Não-Violenta",
    author: "Marshall B. Rosenberg",
    year: 1999,
    category: "Psicologia",
    minutes: 13,
    hook: "Toda violência é a expressão trágica de uma necessidade não atendida.",
    summary: "Marshall Rosenberg oferece um framework para conectar com empatia mesmo em conflitos.",
    tags: ["comunicação", "empatia", "conflitos"],
    file_en: "comunicacao-nao-violenta-en.md",
    title_en: "Nonviolent Communication",
    category_en: "Psychology",
    hook_en: "All violence is the tragic expression of an unmet need.",
    summary_en: "Marshall Rosenberg offers a framework to connect with empathy even in conflicts.",
    tags_en: ["communication", "empathy", "conflicts"]
  }
];
